import { useCallback, useEffect, useState } from 'react'
import { api, errorMessage, jsonBody } from '../lib/api'
type Course = { slug: string; title: string; subtitle: string; price: number; isPublished: boolean; isPurchasable: boolean; lessons: { id: string; title: string; code: string; isPreview: boolean; isPublished: boolean }[] }
export default function AdminCourses() {
  const [courses, setCourses] = useState<Course[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const refresh = useCallback(async () => { setLoading(true); setError(''); try { setCourses(await api<Course[]>('/admin/courses')) } catch(e) { setError(errorMessage(e)) } finally { setLoading(false) } }, [])
  useEffect(() => { void refresh() }, [refresh])
  const save = async (path: string, body: unknown) => { setBusy(true); setError(''); try { await api(`/admin/courses/${path}`, { method: 'PATCH', body: jsonBody(body) }); await refresh() } catch(e) { setError(errorMessage(e)) } finally { setBusy(false) } }
  return <div><h1 className="text-[27px] font-bold">课程管理</h1><p className="mt-2 text-sm text-slate-500">维护价格、发布和试看状态；正文通过仓库文件维护。</p>{error && <p role="alert" className="mt-4 text-red-600">{error} <button onClick={() => void refresh()}>重试</button></p>}{loading ? <p className="py-10" role="status">正在加载课程…</p> : <div className="mt-6 grid gap-4 lg:grid-cols-2">{courses.map((s) => <section key={s.slug} className="card p-5"><span className="text-xs text-brand-600">{s.slug}</span><h2 className="mt-1 text-lg font-semibold">{s.title}</h2><p className="mt-2 text-xs leading-5 text-slate-500">{s.subtitle}</p><form className="mt-4 flex items-center gap-2" onSubmit={(e) => { e.preventDefault(); void save(`stages/${s.slug}`, { price: Number(new FormData(e.currentTarget).get('price')) }) }}><label className="text-sm">价格 ¥ <input name="price" aria-label={`${s.title}价格`} type="number" min={0} max={1000000} step={1} required defaultValue={s.price} key={s.price} className="h-9 w-24 rounded-lg border px-2"/></label><button disabled={busy} className="btn btn-sm btn-outline">保存价格</button></form><div className="my-4 flex gap-4 text-sm"><label><input disabled={busy} type="checkbox" checked={s.isPublished} onChange={(e)=>void save(`stages/${s.slug}`,{isPublished:e.target.checked})}/> 已发布</label><label><input disabled={busy} type="checkbox" checked={s.isPurchasable} onChange={(e)=>void save(`stages/${s.slug}`,{isPurchasable:e.target.checked})}/> 可购买</label></div><ol className="divide-y border-t">{s.lessons.map((l)=><li key={l.id} className="flex flex-wrap items-center justify-between gap-3 py-3 text-xs"><span>{l.code} {l.title}</span><span className="flex gap-3"><label><input disabled={busy} type="checkbox" checked={l.isPublished} onChange={(e)=>void save(`lessons/${l.id}`,{isPublished:e.target.checked})}/> 发布</label><label><input disabled={busy} type="checkbox" checked={l.isPreview} onChange={(e)=>void save(`lessons/${l.id}`,{isPreview:e.target.checked})}/> 试看</label></span></li>)}</ol></section>)}</div>}</div>
}
